name: Build Docker & Deploy Wisecow App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image with incremental build number
      - name: Build Docker image
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/wisecow:${{ github.run_number }}"
          docker build -t $IMAGE_NAME .

      # Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/wisecow:${{ github.run_number }}"
          docker push $IMAGE_NAME

      # Configure kubectl
      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          cp /home/ubuntu/.kube/config $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      # Apply Namespace
      - name: Apply Namespace
        run: kubectl apply -f k8s/wisecow-namespace.yml

      # Apply Cert Manager Issuer (self-signed)
      - name: Apply Cert Manager
        run: kubectl apply -f k8s/selfsigned-clusterissuer.yml

      # Apply Service
      - name: Apply Service
        run: kubectl apply -f k8s/wisecow-service.yml

      # Deploy Application
      - name: Deploy Application
        run: |
          # Apply deployment manifest if not exists
          kubectl apply -f k8s/wisecow-deploy.yml || true
          # Update deployment image with new build number
          kubectl set image deployment/wisecow-deploy wisecow-cont=${{ secrets.DOCKER_USERNAME }}/wisecow:${{ github.run_number }} -n wisecow-app
          # Wait until pod is ready
          kubectl rollout status deployment/wisecow-deploy -n wisecow-app

      # Apply Ingress
      - name: Apply Ingress
        run: kubectl apply -f k8s/wisecow-ingress.yml

